### ISSUE TITLE
Incorrectly named variables

### ISSUE THREAD

**Issue by poort** [nviennot/nginx-tcp-keepalive#1]
First of all thanks for this great module!

I've noticed when I compiled it and used it for the first time nginx wouldn't boot because it didn't recognize the tcp_keepidle and tcp_keepintvl variable.

In the file ngx_http_tcp_keepalive_module.c on line 97 , 113 and 121 the variable tcp_keepalive was declared three times. I've corrected the bottom two and now it seems to work.

**Comment by nviennot** [comment]
Indeed !
Fixed it,
Thanks,
Nico
